theme: minima
title: craiglo bio [GitHub]
author: Craiglo [Craig T. Hunkele]
email: support@craiglo.com
description: open-source, self-hosted, self-built, personal webpage, craiglo bio

# social links
twitter_username: bagelbuttcheeks # DO NOT include the @ character, or else the build will fail!
github_username:  craiglo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
